# Generated by Django 6.0.3 on 2026-03-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assets',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='user',
            name='loans',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
