# Generated by Django 6.0.3 on 2026-03-25 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('UPI', 'UPI'), ('Net Banking', 'Net Banking')], default='Cash', max_length=20)),
                ('mood', models.CharField(choices=[('Happy', 'Happy 😄'), ('Sad', 'Sad 😢'), ('Neutral', 'Neutral 😐'), ('Angry', 'Angry 😠'), ('Excited', 'Excited 🤩'), ('Anxious', 'Anxious 😰')], default='Neutral', max_length=20)),
                ('expense_type', models.CharField(choices=[('Personal', 'Personal Expense'), ('Extra', 'Extra Expense')], default='Personal', max_length=20)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
