# Generated by Django 6.0.3 on 2026-03-25 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_income_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('Personal', '1️⃣ Personal Expenses (Daily Needs)'), ('Extra', '2️⃣ Extra Expenses (Lifestyle / Optional)'), ('Saving', '3️⃣ Savings & Investments'), ('Income', '4️⃣ Income Category')], max_length=20)),
                ('main_category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('icon', models.CharField(default='📌', max_length=10)),
                ('color', models.CharField(default='#6c757d', max_length=20)),
            ],
            options={
                'ordering': ['expense_type', 'main_category', 'sub_category'],
            },
        ),
        migrations.RemoveField(
            model_name='expense',
            name='expense_type',
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.category'),
        ),
    ]
