# Generated by Django 6.0.3 on 2026-04-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_account_dividend_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
