# Generated by Django 6.0.3 on 2026-04-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_subscription_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='expense_type',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Extra', 'Extra'), ('Office', 'Office')], max_length=20),
        ),
    ]
