# Generated by Django 6.0.3 on 2026-04-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_category_expense_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='expense_type',
            field=models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Shopping', 'Shopping'), ('Bills', 'Bills'), ('Others', 'Others')], max_length=20),
        ),
    ]
